import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';

export enum Continent {
  Africa = 'Africa',
  Antarctica = 'Antarctica',
  Asia = 'Asia',
  Europe = 'Europe',
  Oceania = 'Oceania',
  North_America = 'North America',
  South_America = 'South America',
}

@Entity('countries', { synchronize: false, schema: 'public' })
export class Country {
  @PrimaryGeneratedColumn('increment', { type: 'bigint', comment: 'Primary key, autogenerated' })
  id: number;

  @Column('text', { nullable: true, comment: 'Full country name.' })
  name: string;

  @Column('char', { length: 2, nullable: false, comment: 'ISO 3166-1 alpha-2 code.' })
  iso2: string;

  @Column('char', { length: 3, nullable: true, comment: 'ISO 3166-1 alpha-3 code.' })
  iso3: string;

  @Column('text', { nullable: true, comment: 'Local variation of the name.' })
  localName: string;

  @Column({
    type: 'enum',
    enum: Continent,
    nullable: true,
    comment: 'Continent to which the country belongs.',
  })
  continent: Continent;
}
